GestionMusiques/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^musiques/', include('musiques.urls')),
]

musiques/urls.py
from django.conf.urls import url, include
from . import views
from .views import MorceauDetailView, ArtisteDetailView, MorceauListView

app_name = 'musiques'
urlpatterns = [
    url(r'^(?P<pk>\d+)$', MorceauDetailView.as_view(), name='morceau-detail'),
    url(r'^detailArtiste/(?P<pk>\d+)$', ArtisteDetailView.as_view(), name='artiste-detail'),
    url(r'^listemorceau/', MorceauListView.as_view(), name='morceau-liste'),
    ]

musiques/models.py
from django.db import models

class Artiste(models.Model):
    nom = models.CharField(max_length=64)

class Morceau(models.Model):
    nom = models.CharField(max_length=64)
    artiste = models.CharField(max_length=64)
    artiste_fk = models.ForeignKey(Artiste, on_delete=models.CASCADE, null=True)
    date_sortie = models.DateField(null=True)

    def __str__(self):
        return '{seld.titre} ({self.artiste})'.format(self=self)

musiques/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import DetailView, ListView

def morceau_detail(request,pk):
    return HttpResponse('OK')

from django.views.generic import DetailView
from .models import Morceau, Artiste

class MorceauDetailView(DetailView):
    model = Morceau
    template_name = 'musiques/morceau_detail.html'

class ArtisteDetailView(DetailView):
    model = Artiste
    template_name = 'musiques/artiste.html'

class MorceauListView(ListView):
    model = Morceau
    template_name = 'musiques/morceau_list.html'

musiques/templates/musiques/artiste.html
{% extends "musiques/base.html" %}
{% block contenu %}
<p>Artiste : {{object.nom}}</p>
{% endblock %}

musiques/templates/musiques/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="fr">
<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/musiques.css' %}">
    <title>Gestion Musiques</title>
</head>
<body>
    <div class="row">
        <div class="col-lg-11">
            <h1>Gestion de dank music</h1>
                <nav class="content container">
                        <div class="col-md-8">
                                <p><a href="{% url 'musiques:morceau-liste' %}" class="top-menu">Liste des morceaux</a></p>
                            {% block contenu %}
                            {% endblock %}
                        </div>
        </div>
    </div>
</body>
</html>

musiques/templates/musiques/morceau_detail.html
{% extends "musiques/base.html" %}
{% block contenu %}
<h2>Morceau : {{ object.nom }}</h2>
<h2>Artiste : {{ object.artiste }}</h2>
<h2>Date de sortie : {{ object.date_sortie }}</h2>
{% endblock %}

musiques/templates/musiques/morceau_list.html
{% extends "musiques/base.html" %}
{% block contenu %}
<ul>
    {% for morceau in object_list %}
        <li><a href="{% url 'musiques:morceau-detail' pk=morceau.id %}">{{morceau.nom}} - {{morceau.artiste}}</a></li>
    {% endfor %}
</ul>
{% endblock %}